### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [NachiketaVadera/Flashlight#2]
Hello, i am a graphic designer and i'd like to contribute a logo to your project, it's free of course.

**Comment by NachiketaVadera** [comment]
Hey, @dee-y! Sorry for the late reply. Of course I would love that.

**Comment by dee-y** [comment]
Alright i will make one for you soon... Cheers

**Comment by dee-y** [comment]
Hello, what do you think of this design? does it fit into your expectations? if you have modifications to make on it please let me know. If not, how would you like me to export the logo for you, any sizes you'd like?

![flashlight-02](https://user-images.githubusercontent.com/36637989/46117344-a808cf80-c1f8-11e8-82ce-222aa7ec114c.png)

**Comment by NachiketaVadera** [comment]
Hey @dee-y. No modifications because loved your work! If you could, I'd like you to have a look at this link and export the logo accordingly.

Link : [IconHandBook](http://iconhandbook.co.uk/reference/chart/android/)

Also, if you're up for it, I have another request for this app. A GIF that show displays the shake motion and switches on the Flashlight when the shake is detected. Something like [this](https://cdn57.androidauthority.net/wp-content/uploads/2015/05/Chop-Twice-for-flashlight.gif).

Thank you for your amazing work.

**Comment by dee-y** [comment]
Hi, great idea with the gif. What do you think of these? Any changes?
![gif1](https://user-images.githubusercontent.com/36637989/46249947-a70ab480-c429-11e8-96e1-7311e1dcc195.gif)

![gif2](https://user-images.githubusercontent.com/36637989/46249951-b689fd80-c429-11e8-8d0b-8e13b41dadc7.gif)
![gif3](https://user-images.githubusercontent.com/36637989/46249957-c570b000-c429-11e8-8618-90be213d5fbe.gif)

**Comment by NachiketaVadera** [comment]
Great work once again! No changes required.

**Comment by dee-y** [comment]
Great...is it okay i submit a pull request?

**Comment by NachiketaVadera** [comment]
Yes, please do.
